### PR TITLE
get animation working with new version of gganimate

### PR DESCRIPTION
**Pull request by cpsievert**
@rmendels here's roughly what it would take to get animation in plotdap to work with the CRAN version of gganimate. I'm not actually sure this is a good idea since it seems as though the modern gganimate is significantly slower (i.e., you might want to [force users to use this version of gganimate](https://github.com/ropensci/plotdap/issues/4#issuecomment-404717794)). That sort of requirement is typically against CRAN policy, but you could do some workarounds to get plotdap on CRAN while still using a non-CRAN version of gganimate.

### CODE REVIEW

**Comment by rmendels** [comment]
Thanks @cpsievert.  I will look at this.  I was trying several approaches.  Some of it had to do with when are with what you did the animation.

**Comment by rmendels** [comment]
@cpsievert I should add that what you have for tabledap is what I had worked out and that works.  What I was working on was rather than build the animation where you did,  build it in plot.griddap,  and maybe change what is saved in if an animation is being saved.

As long as I am writing,  and since it is a simple change,  to get grids plotting again in base R,  which isn't working,  all you need to do  (referencing lines in Master branch to change lines  450-461 to add a "reset = FALSE", as in:

```r
  # plot the background map
  plot(
    x$layers[[1]],
    xlim = xlim,
    ylim = ylim,
    main = x$mapTitle %||% "",
    col = x$mapFill,
    border = x$mapColor,
    graticule = graticule,
    #setParUsrBB = TRUE,
    bty = "n",
    ...
  )
```

to 

```r
  plot(
    x$layers[[1]],
    xlim = xlim,
    ylim = ylim,
    main = x$mapTitle %||% "",
    col = x$mapFill,
    border = x$mapColor,
    graticule = graticule,
    #setParUsrBB = TRUE,
    bty = "n",
    reset = FALSE,
    ...
  )
```
It took me awhile to dig that up.  Also,  I think i know how to have geom_sf not draw the polygon edges,   but I need to test it.  The fix above works.

**Comment by rmendels** [comment]
@cpsievert okay I have been playing around with the animations.  As is they are either too slow to render or display too quickly.  What I have been trying is having the only option for an animation is to save the file, and I just used  gganimate::transition_states(variable) with no options .  If I read it back in,  and  use gganimate::animate() it works quite nicely.  So for the wind data if I save as set up, it wants about an hour to render and send my machine to never-never land.  If I save it and use animate with:

```r 
my_anim <- x$ggplot
animate(my_anim, nframes = 3, fps =1 )
```

I get a nice animation which took about 2 minutes to render.  This lets the user decide how long to take to render.  I also want to play around with the options in gganimate::transition_states(),  whether it is better to have no options or also include "transition_length" and "state_length".  But whichever,  I am convinced the best option is to only save the animation,  not to render it.

**Comment by rmendels** [comment]
@cpsievert I have gganimate working the way I would like to see it.  I am using transition_manual().  That makes the minimal animation, and makes it easier to get the labels correct.  If the user uses the included print method,  then they get values for nframes,  fps and duration in the function animate() that I have chosen.  The advantage of this is if the user saves the object rather than prints it,  they can then animate with their own desired settings.

I want to take you README file and turn it into a vignette,  separate out the animations,  and show some examples of this.

But progress

**Comment by rmendels** [comment]
@cpsievert okay I have this very close to being ready for CRAN.  I am not good with git/github in these situations,  can you tell me how you would like me to upload what I have done.  What has been done:

1. Problem with overlay of grid in base graphics has been fixed.
2. Turned the README into more extensive vignette,  made a simpler README as CRAN checks did not like the present version.
3. Add some pre-downloaded datasets, otherwise the examples take too long for CRAN.
4. Removed the tests, as again they take too long for CRAN.
5. Added an option in the `print.ggplotdap()` so that the land is printed over the grid,  not vice versa.  Not an elegant solution but too many problems with other solutions
6. Fixed the animation option to work with the new gganimate.
7. Added a new function to change the bounding box to an existing plotdap object.  This is needed to have a plotdap object with animation used in `gganimate::animate()` otherwise the animation is not properly clipped.
8. I had to put myself as  "cre" in the Description file, though I didn't like that.  The person down as "cre" is considered the maintainer, and is the one who gets the emails from CRAN or Winbuilder. 

I am still having problems with the timing of the examples and the length of time to typeset the vignette,  but I would like to submit this to CRAN in the next couple of days,  but don't want to do so without your okay.  If and when plotdap is in CRAN,  I will submit my `rerddapXtracto` package,  which also uses plotdap.

**Comment by rmendels** [comment]
@cpsievert  - also fixed how longitudes are adjusted,  and now can properly cross the dateline,  which was previously creating problems.

**Comment by rmendels** [comment]
@cpsievert - I have the package ready so that it should make it through CRAN.  I would like to leave me as "cre" so that I get the emails,  and would you object if I added myself as "aut" as I have done a fair amount of work on it.  I do not want to submit w/o your okay,   please let me know.

**Comment by cpsievert** [comment]
@rmendels great! I absolutely don't mind adding you as an `"aut"` and passing over `"cre"` (maintainer) to you. I also gave you write access to this repo on GitHub, so feel free to make that change to `DESCRIPTION` and merge away!

**Comment by rmendels** [comment]
I would rather first get the changes in the gganimate branch,  and then look at merger.  Unfortunately my knowledge of git and github isn't great,  I need to make certain I understand what I am doing.  I am trying to remember if the directory I have been working on is from cloning or downloading the zip and working on that.

**Comment by rmendels** [comment]
@cpsievert the changes I have made are now in the gganimate branch.  Other than timing,  I can pass Winbuilder and RHub tests, and on my Mac.  The timing is a misleading because the example time is for all four of the main functions.  I have added that to the CRAN info.  I can submit to CRAN without doing a merge to the master branch,  which I would prefer.  Merge perhaps if and when it is accepted on CRAN, and when I am certain I know what I am doing in doing merge,  so I don't mess anything up.  I also may set up 0.0.1 as a release,  so it is saved.

**Pull request merged**
